apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-stateful-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.0.101
    path: /data/nfs/k8s
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: stateful-pvc
  namespace: target-ns
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  volumeName: nfs-stateful-pv
