apiVersion: v1
kind: Namespace
metadata:
  name: source-ns
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: example-configmap
  namespace: source-ns
data:
  APP_ENV: "production"
  LOG_LEVEL: "info"
---
apiVersion: v1
kind: Secret
metadata:
  name: example-secret
  namespace: source-ns
type: Opaque
data:
  DB_USER: dXNlcm5hbWU=
  DB_PASS: cGFzc3dvcmQ=
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: source-ns
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: example-configmap
            - secretRef:
                name: example-secret
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-stateful-pv
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-storage
  nfs:
    server: 192.168.0.101
    path: /data/nfs/k8s
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: stateful-pvc
  namespace: source-ns
spec:
  storageClassName: nfs-storage
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi


---
apiVersion: v1
kind: Service
metadata:
  name: stateful-service
  namespace: source-ns
spec:
  clusterIP: None
  selector:
    app: stateful-pod
  ports:
    - port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: stateful-pod
  namespace: source-ns
spec:
  serviceName: stateful-service
  replicas: 1
  selector:
    matchLabels:
      app: stateful-pod
  template:
    metadata:
      labels:
        app: stateful-pod
    spec:
      containers:
        - name: my-container
          image: nginx
          ports:
            - containerPort: 80
          volumeMounts:
            - name: data-storage
              mountPath: /usr/share/nginx/html
      volumes:
        - name: data-storage
          persistentVolumeClaim:
            claimName: stateful-pvc
